/* eslint-disable */
const fs = require('fs')
const { spawnSync } = require('child_process')
const path = require('path')

const RPFM_PATH = "D:/programs/rpfm shit/"
const SCHEMA_PATH = `C:/Users/admir/AppData/Roaming/rpfm/config/schemas/schema_wh3.ron`
const PROJECT_NAME = `The_Royal_Armoury_of_Bretonnia`
const schemaPath = SCHEMA_PATH.replace(/\\/g, '/')

try {
    fs.mkdirSync("temp2")
} catch (error) {}

if(!fs.existsSync("graphics_assets.pack")) {
    throw `cannot update game assets! graphics_assets.pack is not found`
}

if(!fs.existsSync( `build/@autogenerated_${PROJECT_NAME}.pack`)) {
    throw `cannot update game assets! ${ `build/@autogenerated_${PROJECT_NAME}.pack`} is not found. Perhaps the project never built?`
}


console.log(`extracting graphics assets so they can be added...`)
spawnSync(`${RPFM_PATH}/rpfm_cli.exe`, [
    '--game', 'warhammer_3', 
    'pack', 
    `extract` , `--folder-path`, `/;temp2`,
    `--pack-path` , `graphics_assets.pack`,   
], {
    stdio: "inherit",
    encoding: 'utf8'
})

console.log(`adding extracted graphics`)
spawnSync(`${RPFM_PATH}/rpfm_cli.exe`, [
    '--game', 'warhammer_3', 
    'pack', 
    `add`, `--pack-path` , `build/@autogenerated_${PROJECT_NAME}.pack`, 
    `-t`, `${schemaPath}`,
    `--folder-path`, `temp2`
], 
{ encoding: 'utf8', stdio: 'inherit' })

console.log(`cleaning up`)
fs.rmSync(`temp2/`, { recursive: true })

console.log(`assets has been updated`)