
namespace TheGrailLordsOfBretonnia {

    /** AUTOGENERATED TYPESCRIPT February 18, 2023, 11:07:15 AM */

    type ThumbnailFilenameToBasicSet = {
        [thumbnailFile: string]: ArmourySystem.BasicSet
    }

    const ARMOURY_DATA: ThumbnailFilenameToBasicSet = {
        
            ["UI/Portraits/Portholes/admiralnelson/bret_lord_massif_1.png"] : {
                FaceId: "face_massif_lord_1",
                HelmetId: "hair_massif_lord1",
                ArmourId: "tabard_massif_lord2",
                WeaponId: "massif_2handed_axe",
                ShieldId: "NONE",
                CapeId: "NONE"
            },
            ["UI/Portraits/Portholes/admiralnelson/bret_lord_massif_2.png"] : {
                FaceId: "face_massif_lord_2",
                HelmetId: "hair_massif_lord2",
                ArmourId: "tabard_massif_lord2",
                WeaponId: "massif_2handed_axe",
                ShieldId: "NONE",
                CapeId: "NONE"
            },
            ["UI/Portraits/Portholes/admiralnelson/bret_lord_massif_3.png"] : {
                FaceId: "face_massif_lord_3",
                HelmetId: "hair_massif_lord3",
                ArmourId: "tabard_massif_lord3",
                WeaponId: "massif_2handed_axe",
                ShieldId: "NONE",
                CapeId: "NONE"
            },
            ["UI/Portraits/Portholes/admiralnelson/bret_lord_massif_4.png"] : {
                FaceId: "face_massif_lord_4",
                HelmetId: "hair_massif_lord4",
                ArmourId: "tabard_massif_lord4",
                WeaponId: "massif_basic_sword",
                ShieldId: "massif_basic_shield",
                CapeId: "NONE"
            },
            ["UI/Portraits/Portholes/admiralnelson/bret_lord_massif_5.png"] : {
                FaceId: "face_massif_lord_8",
                HelmetId: "hair_massif_lord5",
                ArmourId: "tabard_massif_lord5",
                WeaponId: "massif_basic_sword",
                ShieldId: "massif_basic_shield",
                CapeId: "NONE"
            },
    }

    ArmourySystem.RegisterFaction(["wh_main_brt_bretonnia"])
    ArmourySystem.RegisterSubtypeAgent(["admiralnelson_bret_lord_massif_agent_key","admiralnelson_bret_lord_massif_sword_shield_agent_key"])
    for (const [fileName, basicSet] of Object.entries(ARMOURY_DATA)) {
        ArmourySystem.RegisterThumbnailFilenamesToAssociatedBasicSet(fileName, basicSet)
    }
    ArmourySystem.RegisterArmour([
        {
                anciliaryKey: "admiralnelson_debug_naked_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_naked_body"
            },{
                anciliaryKey: "wh_dlc07_anc_armour_armour_of_the_midsummer_sun",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_wh_dlc07_anc_armour_armour_of_the_midsummer_sun"
            },{
                anciliaryKey: "wh_dlc07_anc_armour_cuirass_of_fortune",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_wh_dlc07_anc_armour_cuirass_of_fortune"
            },{
                anciliaryKey: "wh_dlc07_anc_armour_gilded_cuirass",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_wh_dlc07_anc_armour_gilded_cuirass"
            },{
                anciliaryKey: "wh_dlc07_anc_armour_the_grail_shield",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_wh_dlc07_anc_armour_the_grail_shield"
            },{
                anciliaryKey: "wh_main_anc_armour_armour_of_destiny",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_wh_main_anc_armour_armour_of_destiny"
            },{
                anciliaryKey: "wh_main_anc_armour_armour_of_silvered_steel",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_wh_main_anc_armour_armour_of_silvered_steel"
            },{
                anciliaryKey: "wh_main_anc_armour_glittering_scales",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_wh_main_anc_armour_glittering_scales"
            },{
                anciliaryKey: "wh_main_anc_armour_armour_of_fortune",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_wh_main_anc_armour_armour_of_fortune"
            },{
                anciliaryKey: "wh_main_anc_armour_gamblers_armour",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_wh_main_anc_armour_gamblers_armour"
            },{
                anciliaryKey: "admiralnelson_armour_1_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_admiralnelson_armour_1"
            },{
                anciliaryKey: "admiralnelson_armour_2_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_admiralnelson_armour_2"
            },{
                anciliaryKey: "admiralnelson_armour_3_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_admiralnelson_armour_3"
            },{
                anciliaryKey: "admiralnelson_armour_4_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_admiralnelson_armour_4"
            },{
                anciliaryKey: "admiralnelson_armour_5_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_admiralnelson_armour_5"
            },{
                anciliaryKey: "admiralnelson_armour_6_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_admiralnelson_armour_6"
            },{
                anciliaryKey: "admiralnelson_armour_7_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_admiralnelson_armour_7"
            },{
                anciliaryKey: "admiralnelson_armour_8_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_admiralnelson_armour_8"
            },{
                anciliaryKey: "admiralnelson_armour_9_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_admiralnelson_armour_9"
            },{
                anciliaryKey: "admiralnelson_armour_10_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_admiralnelson_armour_10"
            },{
                anciliaryKey: "admiralnelson_debug_naked_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_naked_body"
            },{
                anciliaryKey: "wh_dlc07_anc_armour_armour_of_the_midsummer_sun",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_wh_dlc07_anc_armour_armour_of_the_midsummer_sun"
            },{
                anciliaryKey: "wh_dlc07_anc_armour_cuirass_of_fortune",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_wh_dlc07_anc_armour_cuirass_of_fortune"
            },{
                anciliaryKey: "wh_dlc07_anc_armour_gilded_cuirass",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_wh_dlc07_anc_armour_gilded_cuirass"
            },{
                anciliaryKey: "wh_dlc07_anc_armour_the_grail_shield",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_wh_dlc07_anc_armour_the_grail_shield"
            },{
                anciliaryKey: "wh_main_anc_armour_armour_of_destiny",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_wh_main_anc_armour_armour_of_destiny"
            },{
                anciliaryKey: "wh_main_anc_armour_armour_of_silvered_steel",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_wh_main_anc_armour_armour_of_silvered_steel"
            },{
                anciliaryKey: "wh_main_anc_armour_glittering_scales",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_wh_main_anc_armour_glittering_scales"
            },{
                anciliaryKey: "wh_main_anc_armour_armour_of_fortune",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_wh_main_anc_armour_armour_of_fortune"
            },{
                anciliaryKey: "wh_main_anc_armour_gamblers_armour",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_wh_main_anc_armour_gamblers_armour"
            },{
                anciliaryKey: "admiralnelson_armour_1_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_admiralnelson_armour_1"
            },{
                anciliaryKey: "admiralnelson_armour_2_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_admiralnelson_armour_2"
            },{
                anciliaryKey: "admiralnelson_armour_3_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_admiralnelson_armour_3"
            },{
                anciliaryKey: "admiralnelson_armour_4_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_admiralnelson_armour_4"
            },{
                anciliaryKey: "admiralnelson_armour_5_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_admiralnelson_armour_5"
            },{
                anciliaryKey: "admiralnelson_armour_6_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_admiralnelson_armour_6"
            },{
                anciliaryKey: "admiralnelson_armour_7_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_admiralnelson_armour_7"
            },{
                anciliaryKey: "admiralnelson_armour_8_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_admiralnelson_armour_8"
            },{
                anciliaryKey: "admiralnelson_armour_9_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_admiralnelson_armour_9"
            },{
                anciliaryKey: "admiralnelson_armour_10_armour_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_admiralnelson_armour_10"
            },
    ])
    ArmourySystem.RegisterHelmet([
        {
                anciliaryKey: "admiralnelson_bascinet_closed_crest_pegasus_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_bascinet_closed_crest_pegasus_helmet"
            },{
                anciliaryKey: "admiralnelson_basic_gilded_sallet_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_basic_gilded_sallet_helmet"
            },{
                anciliaryKey: "admiralnelson_chainmail_basic_helmet",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_chainmail_basic_helmet"
            },{
                anciliaryKey: "admiralnelson_dragonhelm_2_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_dragonhelm_2_helmet"
            },{
                anciliaryKey: "admiralnelson_dragonhelm_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_dragonhelm_helmet"
            },{
                anciliaryKey: "admiralnelson_feathered_closed_with_crest_antler_pegasus_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_feathered_closed_with_crest_pegasus_helmet"
            },{
                anciliaryKey: "admiralnelson_feathered_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_feathered_helmet"
            },{
                anciliaryKey: "admiralnelson_feathered_with_crest_antler_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_feathered_with_crest_antler_helmet"
            },{
                anciliaryKey: "admiralnelson_feathered_with_crest_antler_lady_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_feathered_with_crest_antler_lady_helmet"
            },{
                anciliaryKey: "admiralnelson_generic_bascinet_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_generic_bascinet_helmet"
            },{
                anciliaryKey: "admiralnelson_gilded_sallet_crest_guard_closed_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_gilded_sallet_crest_guard_closed_helmet"
            },{
                anciliaryKey: "admiralnelson_gilded_sallet_crest_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_gilded_sallet_crest_helmet"
            },{
                anciliaryKey: "admiralnelson_gilded_sallet_guard_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_gilded_sallet_guard_helmet"
            },{
                anciliaryKey: "admiralnelson_gilded_sallet_guard_helmet_crest_more_feathers_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_gilded_sallet_guard_helmet_crest_more_feathers"
            },{
                anciliaryKey: "admiralnelson_gilded_sallet_lordly_padded_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_gilded_sallet_lordly_padded_helmet"
            },{
                anciliaryKey: "admiralnelson_gilded_sallet_lordly_padded_helmet_crown_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_gilded_sallet_lordly_padded_helmet_crown"
            },{
                anciliaryKey: "admiralnelson_bascinet_closed_crest_pegasus_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_bascinet_closed_crest_pegasus_helmet"
            },{
                anciliaryKey: "admiralnelson_basic_gilded_sallet_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_basic_gilded_sallet_helmet"
            },{
                anciliaryKey: "admiralnelson_chainmail_basic_helmet",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_chainmail_basic_helmet"
            },{
                anciliaryKey: "admiralnelson_dragonhelm_2_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_dragonhelm_2_helmet"
            },{
                anciliaryKey: "admiralnelson_dragonhelm_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_dragonhelm_helmet"
            },{
                anciliaryKey: "admiralnelson_feathered_closed_with_crest_antler_pegasus_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_feathered_closed_with_crest_pegasus_helmet"
            },{
                anciliaryKey: "admiralnelson_feathered_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_feathered_helmet"
            },{
                anciliaryKey: "admiralnelson_feathered_with_crest_antler_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_feathered_with_crest_antler_helmet"
            },{
                anciliaryKey: "admiralnelson_feathered_with_crest_antler_lady_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_feathered_with_crest_antler_lady_helmet"
            },{
                anciliaryKey: "admiralnelson_generic_bascinet_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_generic_bascinet_helmet"
            },{
                anciliaryKey: "admiralnelson_gilded_sallet_crest_guard_closed_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_gilded_sallet_crest_guard_closed_helmet"
            },{
                anciliaryKey: "admiralnelson_gilded_sallet_crest_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_gilded_sallet_crest_helmet"
            },{
                anciliaryKey: "admiralnelson_gilded_sallet_guard_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_gilded_sallet_guard_helmet"
            },{
                anciliaryKey: "admiralnelson_gilded_sallet_guard_helmet_crest_more_feathers_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_gilded_sallet_guard_helmet_crest_more_feathers"
            },{
                anciliaryKey: "admiralnelson_gilded_sallet_lordly_padded_helmet_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_gilded_sallet_lordly_padded_helmet"
            },{
                anciliaryKey: "admiralnelson_gilded_sallet_lordly_padded_helmet_crown_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_gilded_sallet_lordly_padded_helmet_crown"
            },
    ])
    ArmourySystem.RegisterWeapon([
        {
                anciliaryKey: "admiralnelson_bane_of_the_undead_axe_weapon_ancillary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_bane_of_the_undead_axe"
            },{
                anciliaryKey: "wh_dlc07_anc_weapon_sword_of_the_ladys_champion",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_ladys_champion_1handed_sword"
            },
    ])
    ArmourySystem.RegisterShield([
        {
                anciliaryKey: "admiralnelson_the_unbreakable_wall_shield_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_the_unbreakable_wall_shield"
            },{
                anciliaryKey: "admiralnelson_the_ladys_ward_shield_ancillary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_the_ladys_ward_shield"
            },
    ])
    ArmourySystem.RegisterCape([
        {
                anciliaryKey: "admiralnelson_the_cape_of_kings_champion_cape_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_cape_1"
            },{
                anciliaryKey: "admiralnelson_the_cape_of_the_lady_favor_cape_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_cape_2"
            },{
                anciliaryKey: "admiralnelson_the_cape_of_the_lady_favor_cape_2_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_cape_3"
            },{
                anciliaryKey: "admiralnelson_the_cape_of_the_lady_favor_cape_3_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_agent_key",
                assetId: "massif_cape_4"
            },{
                anciliaryKey: "admiralnelson_the_cape_of_kings_champion_cape_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_cape_1"
            },{
                anciliaryKey: "admiralnelson_the_cape_of_the_lady_favor_cape_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_cape_2"
            },{
                anciliaryKey: "admiralnelson_the_cape_of_the_lady_favor_cape_2_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_cape_3"
            },{
                anciliaryKey: "admiralnelson_the_cape_of_the_lady_favor_cape_3_anciliary_key",
                subtypeAgentKey: "admiralnelson_bret_lord_massif_sword_shield_agent_key",
                assetId: "massif_cape_4"
            },
    ])

    //incompatible items
	ArmourySystem.MakeThisItemIncompatibleWithAgent("admiralnelson_bret_lord_massif_agent_key", ["admiralnelson_the_unbreakable_wall_shield_anciliary_key","wh_dlc07_anc_weapon_sword_of_the_ladys_champion","admiralnelson_the_ladys_ward_shield_ancillary_key"])
ArmourySystem.MakeThisItemIncompatibleWithAgent("admiralnelson_bret_lord_massif_sword_shield_agent_key", ["admiralnelson_bane_of_the_undead_axe_weapon_ancillary_key"])

    //conflicting items
	ArmourySystem.MakeThisItemIncompatibleWithItems("admiralnelson_chainmail_basic_helmet_anciliary_key", ["wh_dlc07_anc_armour_armour_of_the_midsummer_sun","wh_dlc07_anc_armour_cuirass_of_fortune","wh_dlc07_anc_armour_gilded_cuirass","wh_dlc07_anc_armour_the_grail_shield","wh_main_anc_armour_armour_of_destiny","wh_main_anc_armour_armour_of_silvered_steel","wh_main_anc_armour_armour_of_fortune"])

}
